_target_: planner.model.senevam.SeNeVAMLightningModule
_convert_: all

hidden_size: 128
dropout: 0.1
num_blocks: 1
num_intentions: 6
num_heads: null
num_neighbors: 128
init_scale: 0.2
optimizer_config:
  lr: 0.0002
  betas:
    - 0.9
    - 0.95
  maximize: false
  weight_decay: 0.01
  min_lr: 0.0000003
